import { BarChart3, Search, ShieldCheck } from 'lucide-react'
import { BrowserRouter, Link, Route, Routes, useNavigate } from 'react-router-dom'
import { SearchBar } from './components/SearchBar'
import { CompanyPage } from './components/CompanyPage'
import type { CompanySearchResult } from './types/company'

function Home() {
  const navigate = useNavigate()
  const selectCompany = (company: CompanySearchResult) => navigate(`/company/${encodeURIComponent(company.symbol)}`)
  return <main className="mx-auto max-w-6xl px-5 pb-16 pt-16 sm:pt-24"><div className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-teal/20 bg-teal/5 px-3 py-1.5 text-xs font-semibold text-teal"><ShieldCheck size={14} /> Real market data · No estimates</div><h1 className="text-5xl font-semibold tracking-[-0.04em] text-ink sm:text-7xl">Understand a company<br /><span className="text-teal">in a few minutes.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-500">A focused workspace for Indian company research. Search a listed business, review its fundamentals, and read the annual P&L without the noise.</p><div className="mt-10"><SearchBar onSelect={selectCompany} /></div><div className="mt-6 flex flex-wrap gap-2 text-xs text-slate-400"><span>Try</span>{['Reliance', 'TCS', 'Infosys'].map((name) => <span key={name} className="rounded-md bg-mist px-2.5 py-1 text-slate-500">{name}</span>)}</div></div><div className="mt-20 grid gap-4 border-t border-line pt-8 sm:grid-cols-3"><Feature icon={<Search size={18} />} title="Search simply" text="Find companies by name or NSE/BSE symbol." /><Feature icon={<BarChart3 size={18} />} title="Read fundamentals" text="See available metrics and annual financials." /><Feature icon={<ShieldCheck size={18} />} title="Honest by default" text="Unavailable data stays N/A, never invented." /></div></main>
}
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="flex gap-3"><div className="rounded-lg bg-teal/10 p-2 text-teal">{icon}</div><div><h3 className="font-semibold text-ink">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div> }
function NotFound() { return <main className="mx-auto max-w-6xl px-5 pb-16 pt-24"><h1 className="text-4xl font-semibold text-ink">Page not found</h1><p className="mt-3 text-slate-500">The page you requested does not exist.</p><Link to="/" className="mt-6 inline-block font-semibold text-teal">Return home</Link></main> }
function App() { return <BrowserRouter><div className="min-h-screen bg-mist/60"><header className="border-b border-line bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link to="/" className="flex items-center gap-2 text-lg font-semibold tracking-tight text-ink"><span className="grid h-8 w-8 place-items-center rounded-lg bg-teal text-white"><BarChart3 size={18} /></span>Market Lens</Link><span className="text-xs font-medium text-slate-400">Indian company research</span></div></header><Routes><Route path="/" element={<Home />} /><Route path="/company/:symbol" element={<CompanyPage />} /><Route path="*" element={<NotFound />} /></Routes><footer className="border-t border-line py-6 text-center text-xs text-slate-400">Market Lens is a frontend demo. Not investment advice.</footer></div></BrowserRouter> }
export default App
